name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Install NativeScript CLI
        run: npm install -g nativescript
        
      - name: Install Project Dependencies
        run: cd my-app && npm install
        
      - name: Build APK
        run: cd my-app && ns build android
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: my-app/platforms/android/app/build/outputs/apk/debug/*.apk
